server:
  port: 8082

spring:
  application:
    name: IDENTITY-SERVICE

  datasource:
    # JDBC අකුරු small විය යුතුයි, database නම නිවැරදිද බලන්න
    url: jdbc:mysql://localhost:3306/unisphere_identity?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: osloCC@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # මේක නිසා තමයි 'users' table එක auto හැදෙන්නේ
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false   # set to true if running service-discovery
    fetch-registry: false         # set to true if running service-discovery
  instance:
    prefer-ip-address: true