server:
  port: 8082 # Identity Service එක දුවන port එක

spring:
  application:
    name: IDENTITY-SERVICE

  # Database සම්බන්ධතාවය
  datasource:
    url: JDBC:mysql://localhost:3300/unisphere_identity?createDatabaseIfNotExist=true
    username: root
    password: 31415
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Settings (Table එක auto හැදෙන්න)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Eureka Client Settings (Service Discovery එකට සම්බන්ධ වෙන්න)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true