server:
  port: 8081

spring:
  application:
    name: booking-service
  # දැනට Database එකක් නැත්නම් Error එක එන එක නතර කරන්න මේක දාන්න
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true